### ISSUE TITLE
Repo on packagist.org

### ISSUE THREAD

**Issue by naxoc** [os2display/default-template-bundle#8]
I needed to pull the code a little quicker than with using vcs in the composer file, so I took the liberty of putting the repository on packagist.org: https://packagist.org/packages/os2display/default-template-bundle - I'll gladly add maintainers and give ownership of the package page to the relevant person in Os2Display.

Let me know if you want maintainership :)

It would also be great if someone with admin-rights to this repo could set up Github auto update hooks as described here: https://packagist.org/about#how-to-update-packages

**Comment by tuj** [comment]
Autoupdate is now enabled.
